PROMPT_TEMPLATES = {
    "extraction": {
        "instruction_job": "You are an expert human resource. You are given a sentence from a job description in German. Highlight all the skills and competencies that are required from the candidate, by surrounding them with tags '@@' and '##'.\n",
        "instruction": "You are an expert human resource. Extract candidates skills in German from the following German sentence, taken from a CV.\n",
        "1shot": "Sentence: Grundlegende Bestimmungen von Urheberrecht und Datenschutz verstehen.\nAnswer: Grundlegende Bestimmungen von @@Urheberrecht## und @@Datenschutz## verstehen.\n",
        "6shots": "Sentence: Grundlegende Bestimmungen von Urheberrecht und Datenschutz verstehen.\nAnswer: Grundlegende Bestimmungen von @@Urheberrecht## und @@Datenschutz## verstehen.\n Sentence: * effektiv und effizient in Projekten mitarbeiten sowie \n Answer: * effektiv und effizient in @@Projekten mitarbeiten## sowie \n Sentence: * Lerneinheiten und didaktisches Vorgehen so gestalten, dass die eigenständige Aktivität der Studierenden gefördert wird. \nAnswer: * Lerneinheiten und @@didaktisches Vorgehen so gestalten##, dass die eigenständige Aktivität der Studierenden gefördert wird. \nSentence: Voraussetzung dafür ist Ihr Feingefühl für Menschen und gute Kenntnisse des aktuellen Arbeits- und Bewerbungsmarkts. Sie wissen, wie und wo Ihre Klienten ihre Fachkenntnisse einbringen können, damit sich die Chancen erhöhen und sie eine passende Arbeit finden. \nAnswer: Voraussetzung dafür ist Ihr @@Feingefühl## für Menschen und gute Kenntnisse des aktuellen Arbeits- und Bewerbungsmarkts. Sie wissen, wie und wo Ihre Klienten ihre Fachkenntnisse einbringen können, damit sich die Chancen erhöhen und sie eine passende Arbeit finden. \nSentence: Direktwerbung, Dialogmarketing, Database-Marketing, Planung von Kampagnen, Adressverwaltung und -selektion, Verfassen von Mailings, Controlling der Kampagnen \nAnswer: Direktwerbung, Dialogmarketing, Database-Marketing, @@Planung von Kampagnen##, Adressverwaltung und -selektion, @@Verfassen von Mailings##, @@Controlling der Kampagnen## \nSentence: Die Teilnehmer können mit einem Tachymeter Punkte und Achsen auf der Baustelle abstecken. \nAnswer: Die Teilnehmer können mit einem Tachymeter Punkte und @@Achsen auf der Baustelle abstecken##.\n",
    },
    "matching": {
        "instruction_job": "You are an expert human resource. You are given a sentence from a job description in German, and a skill extracted from this sentence. Choose from the list of options the one that best match the skill in the context. Answer with the associated letter.\n",
        "instruction": "You are an expert human resource. From a given German sentence from a CV, and a skill extracted from this sentence, choose from the options one or several items that best match the skill in the context. Answer with the associated letter(s).\n",
        "1shot": 'Sentence: Grundlegende Bestimmungen von Urheberrecht und Datenschutz verstehen. \nSkill: Datenschutz. \nOptions: \nA: "Grundsätze des Datenschutzes respektieren" \nB: "Datenschutz verstehen" \nC: "Datenschutz im Luftfahrtbetrieb sicherstellen" \nD: "Datenschutz". \nAnswer: "Datenschutz verstehen", "Datenschutz".\n',
    },
    # "extend_taxonomy_tech": {
    #     "instruction": "I am looking for occurrences of the <SKILL_TYPE> '<NAME>' in a document. However, the author doesn't always refer to this <SKILL_TYPE> using the full name. Generate only a list of 10 other names that I could look for, separated by commas.\n",
    #     "1shot": "Skill: Microsoft Excel \n Answer: Excel, MS Excel, Microsoft Excel, Spreadsheet software by Microsoft, Microsoft's spreadsheet application, Excel program, Excel software, Microsoft's data analysis tool, Microsoft's workbook software, Spreadsheet program by Microsoft\n",
    # },
    # "extend_taxonomy_certif": {
    #     "instruction": "I am looking for occurrences of the <SKILL_TYPE> '<NAME>' in a document. However, the author doesn't always refer to this <SKILL_TYPE> using the full name. Generate only a list of 10 other names that I could look for, separated by commas.\n",
    #     "1shot": "Certification: AWS DevOps Engineer \n Answer: AWS, AWS DevOps Specialist, Amazon DevOps Engineer, AWS DevOps Practitioner, Certified AWS DevOps Professional, AWS DevOps Architect, Amazon Web Services DevOps Expert, AWS DevOps Solutions Engineer, AWS Cloud DevOps Engineer, AWS DevOps Deployment Specialist, AWS DevOps Integration Engineer\n",
    # },
}

## TODO: Think about incorporating the above used in "extend_taxonomy_elements.py" into the Generator
