PROMPT_TEMPLATES = {
    "extraction": {
        "instruction_job": "You are an expert human resource. You are given a sentence from a job description in German. Highlight all the skills and competencies that are required from the candidate, by surrounding them with tags '@@' and '##'.\n",
        "instruction": "You are an expert human resource. Extract candidates skills in German from the following German sentence, taken from a CV.\n",
        "1shot": "Sentence: Grundlegende Bestimmungen von Urheberrecht und Datenschutz verstehen.\nAnswer: Grundlegende Bestimmungen von @@Urheberrecht## und @@Datenschutz## verstehen.\n",
        "6shots": "Sentence: Grundlegende Bestimmungen von Urheberrecht und Datenschutz verstehen.\nAnswer: Grundlegende Bestimmungen von @@Urheberrecht## und @@Datenschutz## verstehen.\n Sentence: * effektiv und effizient in Projekten mitarbeiten sowie \n Answer: * effektiv und effizient in @@Projekten mitarbeiten## sowie \n Sentence: * Lerneinheiten und didaktisches Vorgehen so gestalten, dass die eigenständige Aktivität der Studierenden gefördert wird. \nAnswer: * Lerneinheiten und @@didaktisches Vorgehen so gestalten##, dass die eigenständige Aktivität der Studierenden gefördert wird. \nSentence: Voraussetzung dafür ist Ihr Feingefühl für Menschen und gute Kenntnisse des aktuellen Arbeits- und Bewerbungsmarkts. Sie wissen, wie und wo Ihre Klienten ihre Fachkenntnisse einbringen können, damit sich die Chancen erhöhen und sie eine passende Arbeit finden. \nAnswer: Voraussetzung dafür ist Ihr @@Feingefühl## für Menschen und gute Kenntnisse des aktuellen Arbeits- und Bewerbungsmarkts. Sie wissen, wie und wo Ihre Klienten ihre Fachkenntnisse einbringen können, damit sich die Chancen erhöhen und sie eine passende Arbeit finden. \nSentence: Direktwerbung, Dialogmarketing, Database-Marketing, Planung von Kampagnen, Adressverwaltung und -selektion, Verfassen von Mailings, Controlling der Kampagnen \nAnswer: Direktwerbung, Dialogmarketing, Database-Marketing, @@Planung von Kampagnen##, Adressverwaltung und -selektion, @@Verfassen von Mailings##, @@Controlling der Kampagnen## \nSentence: Die Teilnehmer können mit einem Tachymeter Punkte und Achsen auf der Baustelle abstecken. \nAnswer: Die Teilnehmer können mit einem Tachymeter Punkte und @@Achsen auf der Baustelle abstecken##.\n",
    },
    "matching": {
        "instruction_job": "You are an expert human resource. You are given a sentence from a job description in German, and a skill extracted from this sentence. Choose from the list of options the one that best match the skill in the context. Answer with the associated letter.\n",
        "instruction": "You are an expert human resource. From a given German sentence from a CV, and a skill extracted from this sentence, choose from the options one or several items that best match the skill in the context. Answer with the associated letter(s).\n",
        "1shot": 'Sentence: Grundlegende Bestimmungen von Urheberrecht und Datenschutz verstehen. \nSkill: Datenschutz. \nOptions: \nA: "Grundsätze des Datenschutzes respektieren" \nB: "Datenschutz verstehen" \nC: "Datenschutz im Luftfahrtbetrieb sicherstellen" \nD: "Datenschutz". \nAnswer: "Datenschutz verstehen", "Datenschutz".\n',
    },
}
