nb_resumes: 25
nb_jobs: 200
nb_courses: 500
nb_elem_per_levels: [3,3,3,5]



max_resume_skills: 10
max_job_skills: 10
max_required_course_skills: 3
max_provided_course_skills: 2



dataset_path: data/raw/synthetic/

